language: python
python: 2.7
env:
    - PLONE_VERSION=4.3
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
    - mkdir -p buildout-cache/downloads
    - python bootstrap.py -c travis.cfg
    - bin/buildout -c travis.cfg -N -q -t 3

script: 
    - bin/code-analysis
    - bin/test
after_success:
    - bin/createcoverage run bin/test
    - pip install -q coveralls
    - coveralls
