language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
python: 2.7
matrix:
  - PLONE_VERSION=43

before_install:
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

install:
  - mkdir -p buildout-cache/downloads
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout -c travis.cfg -q -t 7 annotate
  - bin/buildout -vNc travis.cfg -q -t 7

after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls

script:
  - bin/code-analysis
  - bin/test
